GET http://localhost:4000/teams

###

GET http://localhost:4000/leagues/6271386f7ada02bdf9e79c87

###

POST http://localhost:4000/teams
Content-Type: application/json

{
    "name": "Wolves",
    "league": "6271386f7ada02bdf9e79c87",
    "mp": 38,
    "wins": 15,
    "draws": 6,
    "losses": 17,
    "points": 51
}

###

DELETE http://localhost:4000/teams

###

PATCH http://localhost:4000/leagues/6283978d65e8a8bea4c367c0
Content-Type: application/json

{
    "name": "Liga NOS",
    "country": "Portugal"
}