GET http://localhost:4000/leagues

###

GET http://localhost:4000/leagues/

###

POST http://localhost:4000/teams
Content-Type: application/json

{
    "name": "Vizela",
    "league": "6283978d65e8a8bea4c367c0",
    "mp": 34,
    "wins": 7,
    "draws": 12,
    "losses": 15,
    "points": 33
}

###

DELETE http://localhost:4000/teams

###

PATCH http://localhost:4000/leagues/6283978d65e8a8bea4c367c0
Content-Type: application/json

{
    "name": "Liga NOS",
    "country": "Portugal"
}